### ISSUE TITLE
Changing over to ssh-keygen -r

### ISSUE THREAD

**Issue by Gunni** [mindfuckup/Scripts#13]
I'm wondering why this script didn't use this command from the start, it seems to work fine.

**Comment by mindfuckup** [comment]
The aim of this tool is to provide an alternative if ssh-keygen is not installed on the machine. For example, CentOS 7 does not generate the ECDSA SSHFP record. See https://github.com/mindfuckup/Scripts/pull/8#issuecomment-304214484

**Comment by Gunni** [comment]
I did not realize that, sorry

**Comment by mindfuckup** [comment]
No problem, it's not written anywhere. :) I do also use ssh-keygen since I know this tool is available on most distros. But sometimes this self-made script can be handy.
